version: "3.7"

x-logging: &logging
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "100m"

services:
    elastic:
        container_name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
        restart: on-failure
        hostname: elastic
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
        volumes:
            - ./config/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - elasticsearch:/usr/share/elasticsearch/data
        <<: *logging
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
        restart: on-failure
        hostname: logstash
        depends_on:
            - elastic
        ports:
            - 127.0.0.1:5044:5044
            - 127.0.0.1:9600:9600
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        volumes:
            - ./config/logstash/logstash.yaml:/usr/share/logstash/config/logstash.yml:ro
            - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro
        <<: *logging
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
        restart: on-failure
        hostname: kibana
        depends_on:
            - elastic
        ports:
            - 127.0.0.1:5601:5601
        volumes:
            - ./config/kibana.yaml:/usr/share/kibana/config/kibana.yml:ro
        <<: *logging

volumes:
    elasticsearch: